FROM node:14.17.1-alpine3.13

WORKDIR /usr/app

ARG NODE_ENV
ARG HTTP_PROXY
ARG HTTPS_PROXY
ARG EXPRESS_HOST
ARG EXPRESS_PORT
ARG MAX_CLUSTER_FORKS
ARG DOMAIN_CONTROLLER_ARR
ARG LOG_LOCALE
ARG LOG_TIMEZONE
ARG LOG_LOCAL_DATE_FORMAT
ARG LOGGING_LEVEL
ARG REVERSE_PROXY_URI_CONTEXT
ARG REVERSE_PROXY_TARGET_HOST
ARG SESSION_SECRET
ARG REDIS_HOST
ARG REDIS_PORT
ARG RATE_LIMIT_WINDOW_MS
ARG RATE_LIMIT_MAX
ARG RATE_LIMIT_MESSAGE

ENV NODE_ENV ${NODE_ENV}
ENV EXPRESS_HOST ${EXPRESS_HOST}
ENV EXPRESS_PORT ${EXPRESS_PORT}
ENV MAX_CLUSTER_FORKS ${MAX_CLUSTER_FORKS}
ENV DOMAIN_CONTROLLER_ARR ${DOMAIN_CONTROLLER_ARR}
ENV LOG_LOCALE ${LOG_LOCALE}
ENV LOG_TIMEZONE ${LOG_TIMEZONE}
ENV LOG_LOCAL_DATE_FORMAT ${LOG_LOCAL_DATE_FORMAT}
ENV LOGGING_LEVEL ${LOGGING_LEVEL}
ENV REVERSE_PROXY_URI_CONTEXT ${REVERSE_PROXY_URI_CONTEXT}
ENV REVERSE_PROXY_TARGET_HOST ${REVERSE_PROXY_TARGET_HOST}
ENV SESSION_SECRET ${SESSION_SECRET}
ENV REDIS_HOST ${REDIS_HOST}
ENV REDIS_PORT ${REDIS_PORT}
ENV RATE_LIMIT_WINDOW_MS ${RATE_LIMIT_WINDOW_MS}
ENV RATE_LIMIT_MAX ${RATE_LIMIT_MAX}
ENV RATE_LIMIT_MESSAGE ${RATE_LIMIT_MESSAGE}

COPY src src
COPY index.js index.js
COPY package.json package.json

RUN yarn install --pure-lockfile --production --proxy "${HTTP_PROXY}" --https-proxy "${HTTPS_PROXY}" && yarn cache clean

# https://github.com/Yelp/dumb-init
# hadolint ignore=DL3018
RUN apk --no-cache add dumb-init

CMD ["/usr/bin/dumb-init", "node", "."]
